#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : intel-one-mono
Version  : 1.2.1
Release  : 1
URL      : https://github.com/intel/intel-one-mono/archive/refs/tags/V1.2.1.tar.gz
Source0  : https://github.com/intel/intel-one-mono/archive/refs/tags/V1.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : OFL-1.1
Requires: intel-one-mono-data = %{version}-%{release}
Requires: intel-one-mono-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-Makefile-for-install.patch

%description
# Intel One Mono Typeface
![Image of Intel One Mono character set](https://github.com/intel/intel-one-mono/assets/130394986/6c921cf4-f614-41bd-a909-363bb19f9a30)

%package data
Summary: data components for the intel-one-mono package.
Group: Data

%description data
data components for the intel-one-mono package.


%package license
Summary: license components for the intel-one-mono package.
Group: Default

%description license
license components for the intel-one-mono package.


%prep
%setup -q -n intel-one-mono-1.2.1
cd %{_builddir}/intel-one-mono-1.2.1
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1686246736
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1686246736
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/intel-one-mono
cp %{_builddir}/intel-one-mono-%{version}/fonts/otf/license %{buildroot}/usr/share/package-licenses/intel-one-mono/d1f3472dd07ac1b922dcea3e5af9491bc8a4b7fd || :
cp %{_builddir}/intel-one-mono-%{version}/fonts/ttf/license %{buildroot}/usr/share/package-licenses/intel-one-mono/d1f3472dd07ac1b922dcea3e5af9491bc8a4b7fd || :
cp %{_builddir}/intel-one-mono-%{version}/fonts/woff/license %{buildroot}/usr/share/package-licenses/intel-one-mono/d1f3472dd07ac1b922dcea3e5af9491bc8a4b7fd || :
cp %{_builddir}/intel-one-mono-%{version}/fonts/woff2/license %{buildroot}/usr/share/package-licenses/intel-one-mono/d1f3472dd07ac1b922dcea3e5af9491bc8a4b7fd || :
cp %{_builddir}/intel-one-mono-%{version}/license %{buildroot}/usr/share/package-licenses/intel-one-mono/d1f3472dd07ac1b922dcea3e5af9491bc8a4b7fd || :
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fonts/X11/OTF/intelone-mono-font-family-bold.otf
/usr/share/fonts/X11/OTF/intelone-mono-font-family-bolditalic.otf
/usr/share/fonts/X11/OTF/intelone-mono-font-family-italic.otf
/usr/share/fonts/X11/OTF/intelone-mono-font-family-light.otf
/usr/share/fonts/X11/OTF/intelone-mono-font-family-lightitalic.otf
/usr/share/fonts/X11/OTF/intelone-mono-font-family-medium.otf
/usr/share/fonts/X11/OTF/intelone-mono-font-family-mediumitalic.otf
/usr/share/fonts/X11/OTF/intelone-mono-font-family-regular.otf
/usr/share/fonts/X11/TTF/intelone-mono-font-family-bold.ttf
/usr/share/fonts/X11/TTF/intelone-mono-font-family-bolditalic.ttf
/usr/share/fonts/X11/TTF/intelone-mono-font-family-italic.ttf
/usr/share/fonts/X11/TTF/intelone-mono-font-family-light.ttf
/usr/share/fonts/X11/TTF/intelone-mono-font-family-lightitalic.ttf
/usr/share/fonts/X11/TTF/intelone-mono-font-family-medium.ttf
/usr/share/fonts/X11/TTF/intelone-mono-font-family-mediumitalic.ttf
/usr/share/fonts/X11/TTF/intelone-mono-font-family-regular.ttf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/intel-one-mono/d1f3472dd07ac1b922dcea3e5af9491bc8a4b7fd
